### ISSUE TITLE
Należy dookreślić interfejsy wewnętrzne dla Machine Managera

### ISSUE THREAD

**Issue by PatrykCholewa** [Plan-B-PO/docs#10]

**Comment by krzysztofcybulski** [comment]
Zajmę się Tym, jutro wrzucę moją propozycję

**Comment by krzysztofcybulski** [comment]
Oba moduły powinny korzystać z `Zookeepera` i nasłuchiwać zmian na nim.
Z jednej strony będzie `computations/`, do którego dodanie nowego liścia oznacza zgłoszenie nowego obliczenia, a usunięcie anulowanie/zakończenie.
Z drugiej `machines/` gdzie będziemy rejestrować/wyrejestrowywać maszyny.

Machines nasłuchuje na zmiany w `computations/` i odpowiednio wykonuje polecenia na swoich maszynach.

@PatrykCholewa git?

Nie wiem czy `machines/` jest potrzebne, może się okazać, że wystarczy nam `computations/` i machines nasłuchujące na zmiany
