### ISSUE TITLE
Iteracja 2 - Wybór UC

### ISSUE THREAD

**Issue by damianr1602** [Plan-B-PO/docs#26]
Dlaczego rozmyte są UC? Znowu trzeba będzie się wdrażać w czyjś komponent.
Nie można wybrać jak UC, żeby zespoły mogły zajmować się głowie swoim komponentem?

Submit a CN, który to komponent?

@PatrykCholewa 
@krzysztofpcy

**Comment by PatrykCholewa** [comment]
@damianr1602 

- Klient chciał, aby po tej iteracji dużo więcej efektów było widocznych u użytkownika. Szczególnie, dotyczyło to sprawdzania dynamicznego statusu CT oraz wykonywania CT - jest to realizowane przez UC1 i UC10.
- Na pierwszych, niedoszłych testach, prowadzący chciał, żeby było przeprowadzane poprawne submitowanie maszyn - stąd UC11.
- UC12 został dodany, bo jest już przynajmniej częściowo, jak nie całkowicie, zaimplementowany. 

Jak widać, zostały wybrane tylko konieczne przypadki użycia, które i tak musiały się znaleźć. Nie dało się ich nie wybrać.

**Comment by PatrykCholewa** [comment]
> Submit a CN, który to komponent?

Dotyczy to komponentów:

- Machine
- Machine Manager UI
- Machines
