### ISSUE TITLE
Zmiana nazwy użytkownika wyświetlanej w MM UI w scenariuszach testowych.

### ISSUE THREAD

**Issue by Bentozord** [Plan-B-PO/docs#48]
Po wdrożeniu Auth0 posługujemy się user_id, nie mamy zdefiniowanego żadnych username, ponieważ id nadawane są automatycznie po rejestracji email + password. Posługujemy się wszędzie tymi właśnie id'kami. Prośba o zmianę(id wyświetlany jest po rejestracji użytkownika i zalogowaniu na ekranie głównmy MM UI).

**Comment by PatrykCholewa** [comment]
@Bentozord Które konkretnie dokumenty wymagają zmiany?

**Comment by Bentozord** [comment]
Chodzi głownie o MM UI.
Tam, gdzie wyswietlana jest nazwa uzytkownika czyli "zalogowany jako:":
1) tuz po zalogowaniu
2) uc gdzie administrator wyswietla wszystkie maszyny

**Comment by Bentozord** [comment]
Zgodnie z rozmowa, userId moze byc dowolnie wyswietlanie, wiec zgloszenie jest do zamkniecia.
