### ISSUE TITLE
Przenieść informacje o schema, aby były bardziej dostępne po stronie ComputationApplication

### ISSUE THREAD

**Issue by PatrykCholewa** [Plan-B-PO/docs#9]
Obecnie _schema_ znajduje sięw __ComputationStepPackage__, a dostęp do niego jest powiązany poprzez referencję _applicationId_ w __ComputationStep__. Należy uprościć dostęp powiązanie _schema_ z __ComputationApplication__. Warto rozważyć przeniesienie _applicationId_ do __ComputationStepPackage__ też.

___Zgłoszone przez @cetlinB___

**Comment by krzysztofcybulski** [comment]
Czy _schema_ nie powinno zawierać się w **ComputationApplication**?

**Comment by cetlinB** [comment]
@krzysztofpcy @PatrykCholewa w zasadzie nie wiem czemu tak nie było od początku.

**Comment by krzysztofcybulski** [comment]
Na początku tak projektowałem, @PatrykCholewa jeśli są jakieś powody dla wejścia tej zmiany to daj znać, jeśli nie to przywróćmy _schema_ do **ComputationApplication**

**Comment by PatrykCholewa** [comment]
Dałem osobno, żeby nie pobierać schemy, jak się przegląda aplikacje po prostu, bez chęci użycia. Mogę dodać do __ComputationApplicatuon__, jeśli wtedy też potrzebne. @krzysztofpcy ?

**Comment by krzysztofcybulski** [comment]
Okej, najbardziej elegancko byłoby rozdzielić, żeby pobierając listę były zwracane aplikacje bez schema, a pobierając konkretny już z.
Prawdę mówiąc na tym etapie możemy zawsze zwracać schema, w kontekście MVP to nic złego :) 
Więc Twój wybór @PatrykCholewa , ja bym nie kombinował i wwrzucił schema do **ComputationApplication**

**Comment by PatrykCholewa** [comment]
Ok, poprawię
